import { usePageTitle } from '../app/hooks';

/** Placeholder until the full page (docs/PROTOTYPE_SPEC.md Part 5.3) is built. */
export default function Science() {
  usePageTitle('Science');
  return (
    <div className="mx-auto max-w-[1200px] px-4 py-14 sm:px-6">
      <h1 className="text-h2 sm:text-h1">Methods, data and limits</h1>
      <p className="mt-5 max-w-[62ch] text-lead">
        The models behind SAMBHAVYA, the data they learn from, how they are verified, and what this prototype does and does not show.
      </p>
      <section id="limits" className="mt-10 max-w-[70ch] border-t border-line pt-6">
        <h2 className="text-h3">What this prototype is</h2>
        <p className="mt-3 text-body">
          A replay with illustrative values. Scenarios are shaped after real events, but every number, field and score is generated by a
          seeded simulation in the browser. No measured skill is claimed.
        </p>
      </section>
    </div>
  );
}
